# -*- coding: utf-8 -*-
"""BeginnerLevel_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3BVKFrVxA2w1NVtnYQoszewkAGkW6qK
"""

# Beginner level codes
name ="My Name is Ragavan"
print('What is your Name:',name)
StudentId = 566
print('Student Id:',StudentId)
# Data Type check
print(type(name))
print(type(StudentId))

# list
frientlist =['abdul','noufal']
print(frientlist[0])
frientlist.append('irfan')
print(frientlist)

# tuble
days = ('sunday','monday','tuesday')
print(days[0])